### ISSUE TITLE
Occasional crash: "terminate called after throwing an instance of 'std::out_of_range'"

### ISSUE THREAD

**Issue by shssoichiro** [HomeOfVapourSynthEvolution/VapourSynth-DFTTest#12]
I had been experiencing this crash for a long time, very occasionally--it seems to happen about one out of every 20 encodes, and I've reproduced it across two machines on multiple Vapoursynth versions (both Arch Linux, 16 logical cores). The error message I would receive is:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
```

This happens at the start of the encode, and I was finally able to get a backtrace showing that dfttest is the source of the issue. Unfortunately, I wasn't able to get debug symbols in the backtrace (tried compiling dfttest with debug symbols, but I am not a C++ developer by any means and the method I used to get a backtrace is a hack).

Steps to reproduce:

1. Have a vapoursynth script with DFTTest as a filter (I'm not sure if bit depth matters, but all of my filtering is done in YUV420P16).
2. Run `vspipe myfile.vpy . --end 1` over and over again until you receive a crash, it should happen about once every 20 attempts.

Below is the backtrace I was able to print out (again, not exceedingly helpful, but did point to this filter at least):

```
vspipe(+0x6015) [0x55d38c736015]
/usr/lib/libstdc++.so.6(+0xa5c8a) [0x7f8980237c8a]
/usr/lib/libstdc++.so.6(+0xa4c3a) [0x7f8980236c3a]
/usr/lib/libstdc++.so.6(__gxx_personality_v0+0x9b) [0x7f89802373bb]
/usr/lib/libgcc_s.so.1(+0x10f44) [0x7f8980043f44]
/usr/lib/libgcc_s.so.1(_Unwind_RaiseException+0x312) [0x7f89800445e2]
/usr/lib/libstdc++.so.6(__cxa_throw+0x3f) [0x7f8980237f7f]
/usr/lib/libstdc++.so.6(_ZSt20__throw_out_of_rangePKc+0x45) [0x7f898022e4e4]
/usr/lib/vapoursynth/libdfttest.so(+0x829d) [0x7f896cfae29d]
/usr/lib/vapoursynth/libdfttest.so(+0x19b16) [0x7f896cfbfb16]
/usr/lib/vapoursynth/libdfttest.so(+0x7348) [0x7f896cfad348]
/usr/lib/libvapoursynth.so(+0x12b345) [0x7f897f446345]
/usr/lib/libvapoursynth.so(+0x163c7f) [0x7f897f47ec7f]
/usr/lib/libvapoursynth.so(+0x16ca50) [0x7f897f487a50]
/usr/lib/libvapoursynth.so(+0x16c96c) [0x7f897f48796c]
/usr/lib/libvapoursynth.so(_ZNSt6thread8_InvokerISt5tupleIJPFvP12VSThreadPoolRSt6atomicIbEES3_St17reference_wrapperIS5_EEEE9_M_invokeIJLm0ELm1ELm2EEEEvSt12_Index_tupleIJXspT_EEE+0x5f) [0x7f897f48789f]
/usr/lib/libvapoursynth.so(_ZNSt6thread8_InvokerISt5tupleIJPFvP12VSThreadPoolRSt6atomicIbEES3_St17reference_wrapperIS5_EEEEclEv+0x18) [0x7f897f48783c]
/usr/lib/libvapoursynth.so(_ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFvP12VSThreadPoolRSt6atomicIbEES4_St17reference_wrapperIS6_EEEEEE6_M_runEv+0x1c) [0x7f897f487820]
/usr/lib/libstdc++.so.6(+0xd33c4) [0x7f89802653c4]
/usr/lib/libpthread.so.0(+0x9259) [0x7f897fe4d259]
```

**Comment by HolyWu** [comment]
I run it for 100 times but I cannot get this crash. What's the resolution of your video and what arguments were passed to DFTTest?

**Comment by shssoichiro** [comment]
I've had this occur on varying video resolutions including 720x540, 1280x720, and 1920x1080. Parameters to DFTTest are the defaults. This makes me wonder if this is some sort of OS or hardware specific issue... i.e. only Linux or only on machines with 16+ logical cores. (Also the machines in question are AVX2 capable but not AVX512, one is a Ryzen 3700X and the other is a Ryzen 4800H.)

Edit: I also can't seem to reproduce it when I run it in a debugger, which is particularly frustrating.

**Comment by shssoichiro** [comment]
It looks like this is likely not related to DFTTest as I'm getting it even when not using the filter. Maybe just a coincidence that DFTTest is the filter being caught in this backtrace. In addition to it being really difficult to reproduce, I think it makes sense to go ahead and close this.

Thanks for looking into it and attempting to reproduce on your end.
