### ISSUE TITLE
GCC 4.x.x can't compile dfttest

### ISSUE THREAD

**Issue by 4re** [HomeOfVapourSynthEvolution/VapourSynth-DFTTest#3]
https://github.com/4re/vapoursynth-portage/issues/31#issuecomment-195848769
Do you think you can fix this? :(

**Comment by HolyWu** [comment]
Does it compile with GCC5, but not with GCC4?

**Comment by HolyWu** [comment]
Well, I just try GCC 4.9.3 in MinGW64 and it compiles successfully...

**Comment by 4re** [comment]
It does not compile for @Q3CPMA with 4.9.3, and I did test with 4.8.5 too, buy that's somewhat unreliable because my system is running on GCC 5.3.0.

For me 5.3.0 is OK on Linux, maybe @Q3CPMA can give a try at it (and use live ebuild if you do).

I was asking because the error itself suggests something about name mangling, and stuff.

The problem is GCC 5.3.0 breaks ABI and is not marked as stable on Gentoo.

**Comment by ghost** [comment]
I have found the error, only `./configure --extra-cxxflags="-mavx"` gives me errors (it compiles flawlessly without). It's included in my `-march=native`

**Comment by ghost** [comment]
The faulty logic is in `vectorclass.h`. Both `"vectorf128.h"` and `"vectorf256.h"` can be (and are) included at the same time. They both define those select{f,d}.

**Comment by 4re** [comment]
Did you try the live ebuild? That should be fixed there. And that's strange, on my machine `-mno-xop` was fixing it, no need to `-mno-avx` there.

EDIT: Oh wait, was fixing it with GCC 5. Now I tested GCC 4 again with `-mno-avx` and it works. Every compiler version has it's own bugs. :/
