### ISSUE TITLE
A make error

### ISSUE THREAD

**Issue by vdeng-ai** [HomeOfVapourSynthEvolution/VapourSynth-DFTTest#7]
**when I do** 
./autogen.sh
./configure
make

**It comes to this error:**
  CXX      DFTTest/DFTTest.lo
  CXX      DFTTest/vectorclass/instrset_detect.lo
  CXX      DFTTest/DFTTest_SSE2.lo
  CXX      DFTTest/libavx2_la-DFTTest_AVX2.lo
  CXXLD    libavx2.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    libdfttest.la
/usr/bin/ld: /usr/local/lib/libfftw3f.a(apiplan.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3f.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:529: recipe for target 'libdfttest.la' failed
make: *** [libdfttest.la] Error 1

I don't know how to recompile with -fPIC.
Thanks in advance for your help.

**Comment by HolyWu** [comment]
You probably need to rebuild your fftw3f with `./configure CFLAGS=-fPIC`, or rebuild your fftw3f as shared library.

**Comment by vdeng-ai** [comment]
Rebuild  fftw3f with ./configure --enable-float  --enable-shared .
Solved.
