### ISSUE TITLE
Race conditions and possible crashes due to changing locale

### ISSUE THREAD

**Issue by myrsloik** [HomeOfVapourSynthEvolution/VapourSynth-DFTTest#9]
You can't change the locale if you're a library. It affects everything else that's also loaded and can actually cause locale related operations in other threads to crash. Apart from all the fun logic errors that can happen in applications that at least assume the decimal separator to be constant.

Just use sscanf_l (_sscanf_l on windows) and do it right. Or use C++ streams where the locale can be set locally as well.

**Comment by myrsloik** [comment]
Or the other way. Simply convert the arguments to a float array which makes more sense.

**Comment by HolyWu** [comment]
Thanks for the information. Haven't known that it will have such an influence. I will fix it soon.

By the way I remember seeing KNLMeansCL change the locale for the decimal point issue too.
